steps:
#- name: 'gcr.io/mlops-353508/zip-tool'
  #args: [ '-x', '/.git*', '-r', 'zipfile.zip', '.']
  #dir: Upload to google cloud storage
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', 'zipfile.zip', 'gs://mlops-353508-kubeflowpipelines-default'