steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    
  # Compile pipeline
  - name: 'python'
    entrypoint: 'python'
    args: ['pipeline.py']
    id: 'compile'
    
  # Upload compiled pipeline to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'kubeflow.zip', 'gs://mlops-353508-kubeflowpipelines-default']
    id:  'upload'
    waitFor: ['compile']  
    
options:
 logging: CLOUD_LOGGING_ONLY
